#!/usr/bin/env python

def build(bld):
	prog = bld(features='cc cprogram')
	# symbolic name used to reference this object
	prog.name = 'rui-bridge.program'
	# name of the resulting program
	prog.target = 'rui-bridge'
	prog.source = 'rui-bridge.vala'
	# libraries to link against
	prog.uselib = ['GUPNP', 'GSSDP']
	# Vala packages to use
	prog.packages = 'gupnp-1.0'
	# Extra vapi dirs
	prog.vapi_dirs = '../vapi'
	# Enable threading
	#prog.threading = True
	# Turn off worthless warnings from the C compiler
	prog.cflags = '-w'
