#!/usr/bin/env python

def build(bld):
	prog = bld(features='cc cprogram')
	# symbolic name used to reference this object
	prog.name = 'hello-gtk.program'
	# name of the resulting program
	prog.target = 'hello-gtk'
	prog.source = 'hello-gtk.vala'
	# libraries to link against
	prog.uselib = 'GTK+'
	# Vala packages to use
	prog.packages = 'gtk+-2.0'
	# Extra vapi dirs
	#prog.vapi_dirs = '../my_lib'
	# Enable threading
	#prog.threading = True
